version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    labels:
      - "tool: github actions"
    commit-message:
      prefix: "⬆️ "

  - package-ecosystem: uv
    versioning-strategy: increase
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    labels:
      - "topic: dependencies"
    commit-message:
      prefix: "⬆️ "
