version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    target-branch: master
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
