version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    labels:
      - "tool: github actions"
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    target-branch: master
    labels:
      - "topic: dependencies"
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
