changelog:
  categories:
    - title: API Changes
      labels:
        - "stubs: api change"
        - "stubs: api change - undocumented"
        - "topic: deprecation"
    - title: Improvements
      labels:
        - "is: feature"
        - "stubs: incomplete"
    - title: Fixes
      labels:
        - "is: fix"
        - "stubs: incorrect"
    - title: Dependency updates
      labels:
        - "topic: dependencies"
    - title: Other Changes
      labels:
        - "*"
