changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - "is: breaking"
    - title: 👽️ SciPy Changes
      labels:
        - "stubs: api change"
        - "stubs: api change - undocumented"
        - "topic: upstream release"
        - "topic: deprecation"
    - title: ✨ Improvements
      labels:
        - "is: feature"
        - "stubs: incomplete"
    - title: 🐛 Fixes
      labels:
        - "is: fix"
        - "stubs: incorrect"
    - title: ✅ Testing
      labels:
        - "topic: testing"
    - title: ⬆️ Dependencies
      labels:
        - "topic: dependencies"
    - title: Other Changes
      labels:
        - "*"
