generated_code_marker: "@generated"
blacklist_patterns: []
repo_root: "."
formatter:
  - "./.venv/bin/ruff"
  - "format"
  - "--stdin-filename=__generated__.pyi"
  - "-"
modules:
  - "libcst.codemod.commands"
  - "codegen.mods"
