name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  OLDEST_SUPPORTED_PYTHON: "3.10"
  OLDEST_SUPPORTED_NUMPY: "1.24.3"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"

      - run: |
          pipx install poetry poethepoet
          poetry config virtualenvs.in-project true --local

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: install
        run: poetry install --with=codegen

      - name: lint
        run: poe lint

      - name: basedmypy
        run: poe mypy

      - name: basedpyright
        run: poe pyright

  typetest:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          pipx install poetry poethepoet
          poetry config virtualenvs.in-project true --local

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: install
        run: poetry install

      - name: typetest
        run: poe typetest

      - name: stubtest
        run: poe stubtest

  typetest-oldest-supported-numpy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          pipx install poetry poethepoet
          poetry config virtualenvs.in-project true --local

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.OLDEST_SUPPORTED_PYTHON }}
          cache: poetry

      - name: install
        run: |
          poetry install
          poetry run pip install --upgrade numpy==$OLDEST_SUPPORTED_NUMPY

      - name: typetest
        run: poe typetest

      - name: stubtest
        run: poe stubtest
