name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint-and-typecheck:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"

      - run: |
          pipx install poetry poethepoet
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: install
        run: poetry install --with=codegen

      - name: lint
        run: poe lint

      - name: typetest
        run: poe typetest

      - name: basedmypy
        run: poe mypy

      - name: basedpyright
        run: poe pyright

  stubtest:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry poethepoet

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: install
        run: poetry install

      - name: Run stubtest
        run: poe stubtest
